### ISSUE TITLE
ImportError: No module named 'taiga'

### ISSUE THREAD

**Issue by tititestor** [erikw/taiga-stats#1]
Hello,
I'm on ubuntu 16.04 LTS server.
My Taiga system works fine, so I installed taiga-stats and i have following error.

Could you help me?
BR,
Titi
```
 ./taiga-stats -h
Traceback (most recent call last):
  File "./taiga-stats", line 12, in <module>
    import taiga
ImportError: No module named 'taiga'
```

**Comment by erikw** [comment]
So apparently `taiga` module can't be found in your python path. Make sure that `taiga-stats` and `taiga` are using the same python version (should be py3 both). Did you install the dependencies with `pip3 install -r requirements.txt`? Using virtualenv? :)

**Comment by tititestor** [comment]
Hi Erik,
Thanks for your help.
I don't use virtualenv.
So, I launched "pip3 install -r requirements.txt" instead of "pip install -r requirements.txt"
and now, I have 
`./taiga-stats -h
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./taiga-stats", line 15, in <module>
    import matplotlib.pyplot as plt
  File "/home/taiga/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/taiga/.local/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/taiga/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/home/taiga/.local/lib/python3.5/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/home/taiga/.local/lib/python3.5/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/taiga/.local/lib/python3.5/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
`

**Comment by erikw** [comment]
Hmm this could be a missing requirement possibly. Could you try using the virtualenv approach found in the README, just to make sure that it's really a missing dependency in a clean environment? :)

**Comment by tititestor** [comment]
Ok, I will try monday.

Best regards,
Titi

**Comment by tititestor** [comment]
Thanks

**Comment by tititestor** [comment]
Same problem on virtual env. (ImportError: No module named '_tkinter', please install the python3-tk package)
So, I install python3-tk package and WORKS !!!!

Thanks for you help.
